name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: 15
      - shell: bash
        name: Importing Private GPG Key
        env:
          gpg_private_key: ${{ secrets.gpg_private_key }}
        run: |
          printf "%s" "$gpg_private_key" | gpg --import --batch --yes
      - name: Getting Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Release with nexus-staging-maven-plugin
        env:
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          ossrh_login: ${{ secrets.ossrh_login }}
          ossrh_pass: ${{ secrets.ossrh_pass }}
        run: |
          mvn versions:set -DnewVersion="${{ env.RELEASE_VERSION }}"
          mvn -B -s .mvn/settings.xml -P release deploy --file pom.xml -pl OktaneCore -am
