name: docs

on:
  push:
    branches: [ master ]

jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Build docs with Maven
        run: mvn javadoc:aggregate -pl :OktaneCore,:Oktane4J

      - name: Copy to Documentation Website Location
        run: |
          rm -rf docs
          mkdir docs
          mkdir docs/OktaneCore
          mkdir docs/Oktane4J
          cp -rf OktaneCore/target/site/apidocs/. docs/OktaneCore
          cp -rf Oktane4J/target/site/apidocs/. docs/Oktane4J

      - name: Tidy up the javadocs
        id: tidy
        uses: cicirello/javadoc-cleanup@v1
        with:
          path-to-root: .

      - name: Log javadoc-cleanup output
        run: |
          echo "modified-count = ${{ steps.tidy.outputs.modified-count }}"

      - name: Commit documentation changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Kieran Boyle'
            git config --global user.email 'kayrenhi@gmail.com'
            git add -A
            git commit -m "Automated API website updates."
          fi