name: Release

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[release skip]')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Get Snapshot Verion
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r .github/scripts/requirements.txt
            echo "version=$(python .github/scripts/auto_version.py com.github.k-boyle Oktane)" >> $GITHUB_ENV

      - name: Get Tag Verion
        if: github.event_name == 'release' && github.event.action == 'created'
        run: echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: JDK16 Setup
        if: ${{ env.version }}
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - shell: bash
        if: ${{ env.version }}
        name: Importing Private GPG Key
        env:
          gpg_private_key: ${{ secrets.gpg_private_key }}
        run: |
          printf "%s" "$gpg_private_key" | gpg --import --batch --yes

      - name: Deployment
        if: ${{ env.version }}
        env:
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          ossrh_login: ${{ secrets.ossrh_login }}
          ossrh_pass: ${{ secrets.ossrh_pass }}
          version: ${{ env.version }}
          MAVEN_OPTS: "--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"
        run: |
          mvn versions:set -DnewVersion="$version"
#          todo fix this
          mvn -B -s .github/maven/settings.xml -P release deploy --file pom.xml -pl Oktane,Oktane4J -am