name: Snapshot Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Update Pip, Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r .scripts/requirements.txt

      - name: Get Snapshot Version
        run: |
          echo "snapshot_version=$(python .scripts/auto_version.py com.github.k-boyle Oktane)" >> $GITHUB_ENV

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Importing Private GPG Key
        env:
          gpg_private_key: ${{ secrets.gpg_private_key }}
        run: |
          printf "%s" "$gpg_private_key" | gpg --import --batch --yes

      - name: Release with nexus-staging-maven-plugin
        env:
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          ossrh_login: ${{ secrets.ossrh_login }}
          ossrh_pass: ${{ secrets.ossrh_pass }}
          snapshot_version: ${{ env.snapshot_version }}
          
        run: |
          mvn versions:set -DnewVersion="$snapshot_version"
          mvn -B -s .mvn/settings.xml -P release deploy --file pom.xml -pl OktaneCore -am